import { useEffect, useRef, useState } from 'react';
import { Html5Qrcode } from 'html5-qrcode';

export default function QRScanner({ onScan, onClose, currentQRToken }) {
  const [cameraError, setCameraError] = useState('');
  const [isScanning, setIsScanning] = useState(false);
  const scannerRef = useRef(null);
  const hasScannedRef = useRef(false);

  useEffect(() => {
    const regionId = 'qr-reader-container';
    const html5QrCode = new Html5Qrcode(regionId);
    scannerRef.current = html5QrCode;
    hasScannedRef.current = false;

    const qrCodeSuccessCallback = (decodedText) => {
      if (hasScannedRef.current) return;
      hasScannedRef.current = true;
      setIsScanning(false);
      
      // Stop scanner before calling onScan
      html5QrCode
        .stop()
        .then(() => {
          html5QrCode.clear();
          onScan(decodedText);
        })
        .catch((err) => {
          console.warn('Error stopping scanner after success:', err);
          onScan(decodedText);
        });
    };

    const qrCodeErrorCallback = (errorMessage) => {
      // Normal frame-by-frame non-detection errors are suppressed
    };

    const config = {
      fps: 10,
      qrbox: { width: 250, height: 250 },
      aspectRatio: 1.0,
    };

    html5QrCode
      .start(
        { facingMode: 'environment' },
        config,
        qrCodeSuccessCallback,
        qrCodeErrorCallback
      )
      .then(() => {
        setIsScanning(true);
        setCameraError('');
      })
      .catch((err) => {
        console.warn('Camera start error:', err);
        setCameraError(
          typeof err === 'string'
            ? err
            : 'Camera access denied or no camera device found on this system.'
        );
        setIsScanning(false);
      });

    return () => {
      if (html5QrCode.isScanning) {
        html5QrCode
          .stop()
          .then(() => html5QrCode.clear())
          .catch((e) => console.warn('Cleanup error on unmount:', e));
      }
    };
  }, [onScan]);

  const handleSimulateScan = () => {
    if (!currentQRToken) {
      alert('No active QR Token generated by admin yet.');
      return;
    }
    if (scannerRef.current && scannerRef.current.isScanning) {
      scannerRef.current
        .stop()
        .then(() => scannerRef.current.clear())
        .catch(() => {});
    }
    // Compact payload matching QRGenerator output
    const compact = {
      l: currentQRToken.locationId,
      t: currentQRToken.token || currentQRToken.tokenId,
      g: Math.floor(new Date(currentQRToken.generatedAt).getTime() / 1000),
    };
    onScan(JSON.stringify(compact));
  };

  const handleSimulateExpiredScan = () => {
    if (scannerRef.current && scannerRef.current.isScanning) {
      scannerRef.current
        .stop()
        .then(() => scannerRef.current.clear())
        .catch(() => {});
    }
    const fakeExpired = {
      t: 'tok_expired_old_9999',
      l: 'loc-001',
      g: 1724140800,
    };
    onScan(JSON.stringify(fakeExpired));
  };

  return (
    <div className="scanner-modal-overlay">
      <div className="scanner-modal fade-in" role="dialog" aria-modal="true">
        <div className="scanner-modal-header">
          <div className="scanner-title-wrap">
            <span className="scanner-icon">📷</span>
            <h2 className="scanner-title">Scan Station QR Code</h2>
          </div>
          <button
            className="scanner-close-btn"
            onClick={onClose}
            aria-label="Close scanner"
          >
            ✕
          </button>
        </div>

        <div className="scanner-viewport-wrap">
          <div id="qr-reader-container" className="scanner-viewport" />
          
          <div className="scanner-guide-overlay">
            <div className="scanner-corner top-left" />
            <div className="scanner-corner top-right" />
            <div className="scanner-corner bottom-left" />
            <div className="scanner-corner bottom-right" />
            <div className="scanner-laser" />
          </div>
        </div>

        {cameraError && (
          <div className="scanner-error-box">
            <span className="error-icon">⚠️</span>
            <div className="error-text">
              <p><strong>Camera Notice:</strong> {cameraError}</p>
              <p className="error-sub">
                You can use the simulation button below for browser testing.
              </p>
            </div>
          </div>
        )}

        <div className="scanner-footer">
          <p className="scanner-hint">
            Point camera directly at the Administrator's station QR display.
          </p>

          <div className="scanner-test-actions">
            <button
              id="btn-simulate-scan"
              type="button"
              className="btn-simulate-scan"
              onClick={handleSimulateScan}
            >
              ⚡ Test Scan Current Station QR
            </button>

            <button
              id="btn-simulate-expired"
              type="button"
              className="btn-simulate-expired"
              onClick={handleSimulateExpiredScan}
            >
              ⚠️ Test Expired Token
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
